config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'
  
  devise_for :users

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_test_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_test_answers
    errors.add(:answers) if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  validates :description, presence: true
  validates :title, presence: true, uniqueness: true

  RULES = %i[first category level]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  EXCERPT_LIMIT = 25

  def excerpt
    question.body.truncate(EXCERPT_LIMIT)
  end

  def hash_url
    url[/gist.github.com\/(\w+)/, 1]
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  scope :by_category, -> (category_title) {
    joins('JOIN categories ON tests.category_id = categories.id').where('categories.title = ?', category_title)
  }
  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { by_level(0..1) }
  scope :medium, -> { by_level(2..4) }
  scope :hard, -> { by_level(5..Float::INFINITY) }

  def self.titles_by_category(category_name)
    joins(:category).by_category(category_name).order(title: :desc).pluck(:title)
  end

  def self.ready_to_pass
    joins(:questions).group('id')
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  PASSAGE_LIMIT = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def passed?
    success_level >= PASSAGE_LIMIT
  end

  def success_level
    (correct_questions.to_f / test.questions.count * 100).round(0)
  end

  def timer
    test.timer * 60
  end

  def time_left
    self.timer == 0 ? 0 : self.timer - (Time.now - created_at.to_time)
  end

  def expired?
    self.time_left < 0
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test'
  has_many :gists
  has_and_belongs_to_many :badges

  validates :first_name, presence: true
  validates :last_name, presence: true

  def tests_by_level(level)
    self.tests.by_level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end

  def show
    @badge = Badge.find(params[:id])
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.ready_to_pass
  end

  def start
    if(@test.questions.any?)
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    else
      redirect_to tests_path, flash: { danger: 'There are no questions in this test.' }
    end
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test not found!'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_year
    Date.today.year
  end

  def github_url(author, repo)
    "#{author} #{link_to 'TestGuru', repo}".html_safe
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.persisted? ? "Edit #{question.test.title} Question" : "Create New #{question.test.title} Question"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    test.persisted? ? "Edit #{@test.title} Test" : "Create New Test"
  end
end

app/views/admin/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Gists', admin_gists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t('badges'), admin_badges_path, class: "nav-link" %>
        </li>
      </ul>
    </div>

    <span class="navbar-text">
      <% if user_signed_in? %>
        <%= t('welcome_master', first_name: current_user.first_name, last_name: current_user.last_name).html_safe %> |
        <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to t('signup'), new_user_registration_path %> |
        <%= link_to t('login'), new_user_session_path %>
      <% end %>
    </span>
    
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/header' %>

    <div class="container">

      <%= render 'shared/flash' %>

      <%= yield %>
      
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/header' %>

    <div class="container pt-3">
      
      <%= render 'shared/flash' %>

      <%= yield %>
      
    </div>

    <%= render 'shared/footer' %>
    
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <% if key == 'alert' %>
    <%= content_tag :div, message, class: 'alert alert-danger', role: 'alert' %>
  <% elsif key == 'notice' %>
    <%= content_tag :div, message, class: 'alert alert-primary', role: 'alert' %>
  <% else %>
    <%= content_tag :div, message, class: "alert alert-#{key}", role: 'alert' %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer style="margin-top: 30px; padding: 15px; background: #777; color: #fff;">
  <div class="wrapper" style="display: flex; justify-content: space-between">
    <div>
      <%= current_year %> 
      <%= github_url t('.author'), 'https://github.com/nikitoooid/test-guru/' %>
    </div>
    <div><a href="https://thinknetica.com/"><%= t('.credits') %></a></div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
    <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to t('admin_panel'), admin_tests_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Gists', admin_gists_path, class: "nav-link" %>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to t('badges'), badges_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('feedback'), new_feedback_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>

    <span class="navbar-text">
      <% if user_signed_in? %>
        <%= t('welcome_guru', name: current_user.first_name).html_safe %> |
        <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to t('signup'), new_user_registration_path %> |
        <%= link_to t('login'), new_user_session_path %>
      <% end %>
    </span>
    
  </div>
</nav>