config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'
  
  devise_for :users

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  PASSAGE_LIMIT = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.index(current_question) + 1
  end

  def passed?
    success_level >= PASSAGE_LIMIT
  end

  def success_level
    (correct_questions.to_f / test.questions.count * 100).round(0)
  end

  def timer
    test.timer * 60
  end

  def time_left
    self.timer == 0 ? 0 : self.timer - (Time.now - created_at.to_time)
  end

  def expired?
    self.time_left < 0
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update gist]

  def show
  end

  def result
    @received_badges = BadgeService.new(@test_passage).call
  end

  def gist
    new_gist = GistQuestionService.new(@test_passage.current_question)
    result = new_gist.call

    if new_gist.success?
      flash_options = { notice: t('.success', url: result.html_url) }
      current_user.gists.create(question: @test_passage.current_question, url: result.html_url )
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  def update
    @test_passage.passed = true if @test_passage.passed?

    params[:answer_ids].nil? ? flash.now[:danger] = t('.no_answer') :  @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.expired?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/_badge.html.erb
<div class="col-md-3 mt-4">
  <div class="card">
    <%= image_tag badge.img_name, class: "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title">
        <%= badge.title %>
      </h5>
      <p class="card-text">
        <%= badge.description %>
      </p>

      <%= link_to t('show'), badge_path(badge), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<div>
  <% if @test_passage.passed? %>
    <% css_class = 'green_font' %>
    <%= content_tag :p, t('.passed') %>
  <% else %>
    <% css_class = 'red_font' %>
    <%= content_tag :p, t('.failed') %>
  <% end %>
</div>

<p>
  <%= content_tag :p, t('.correct_answers', level: @test_passage.success_level), class: css_class %>
</p>

<div class="row">
  <%= render @received_badges %>
</div>

<%= link_to t('.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<%= content_tag :div, nil,
                class: 'passage_timer',
                data: { timer: @test_passage.time_left } %>

<p>
  <%= t('.counter', current: @test_passage.current_question_number, total: @test_passage.test.questions.count) %>
</p>

<%= content_tag :div,
                class: 'progress',
                data: { progress: (@test_passage.current_question_number.to_f - 1) / @test_passage.test.questions.count * 100 } do %>
  <div class="progress-bar"></div>
<% end %>

<p>
  <%= @test_passage.current_question.body %>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false  do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next'), class: 'submit' %></p>
<% end %>