config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'
  
  devise_for :users

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_test_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_test_answers
    errors.add(:answers) if question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :set_answer, only: %i[show edit update destroy]
  before_action :set_question, only: %i[new create]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), flash: { success: 'Answer created.' }
    else
      flash[:danger] = 'Answer not created!'
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), flash: { primary: 'Answer updated.' }
    else
      flash[:danger] = 'Answer not updated!'
      render :edit
    end
  end

  def destroy
    @answer.destroy

    redirect_to admin_question_path(@answer.question), flash: { danger: 'Answer deleted.' }
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Show', admin_answer_path(answer) %>
  <%= link_to 'Edit', edit_admin_answer_path(answer) %>
  <%= link_to 'Delete', admin_answer_path(answer), method: :delete, data: {confirm: 'Are you sure?'} %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>
  
  <%= form.submit %>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>

<%= link_to 'Back to question', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>

<%= link_to 'Back to question', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back to question', admin_question_path(@answer.question) %>