config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'
  
  devise_for :users

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index show]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :set_test, only: %i[new create]
  before_action :set_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show

  end

  def new
    @question = @test.questions.new
  end

  def edit
    
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question), flash: { success: 'Question created!' }
    else
      flash[:danger] = 'Question not created!'
      render :new
    end
  end

  def update
    
    if @question.update(question_params)
      redirect_to admin_question_path(@question), flash: { primary: 'Question updated!' }
    else
      flash[:danger] = 'Question updating failed!'
      render :edit
    end 
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test), flash: { danger: 'Question deleted.' }
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question not found!'
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.persisted? ? "Edit #{question.test.title} Question" : "Create New #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [:admin, @test, @question] do |form| %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :question_body, rows: 7, cols: 60  %>
  </p>
  
  <%= form.submit %>

<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('show'), admin_question_path(question) %></td>
  <td><%= link_to t('edit'), edit_admin_question_path(question) %></td>
  <td><%= link_to t('delete'),
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back to test', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back to test', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1>Question</h1>
<p><%= @question.body %></p>

<h2>Answers</h2>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<%= link_to 'Edit question', edit_admin_question_path(@question) %>
<%= link_to 'Back to test', admin_test_path(@question.test) %>